In [ ]:
题目1：最大利润问题（生产计划）
某工厂生产两种产品 A 和 B。每件产品的利润分别为 40 元和 30 元。产品 A 需要 2 小时的机器时间和 1 小时的人工时间，产品 B 需要 1 小时的机器时间和 2 小时的人工时间。每天最多有 100 小时机器时间和 80 小时人工时间。问：每天应生产多少件 A 和 B 才能使利润最大？

要求：

建立线性规划模型；

解出最大利润及对应的产品数量。



In [7]:
import cvxpy as cp
import numpy as np

a=np.array([40,30])#定义目标函数
b=np.array([[2,1],[1,2]])#定义约束项
c=np.array([100,80])#定义约束常量
x=cp.Variable(2,integer=True)#定义x
obj=cp.Maximize(a@x)#构造目标函数
cons=[b@x<=c,x>=0]
prob=cp.Problem(obj,cons)#构建问题
prob.solve()
print(x.value)
prob.value

[40. 20.]


2200.0

In [ ]:
题目2：最小成本问题（原料配比）
一家食品公司需要混合两种原料 A 和 B 以生产一种饲料，每千克饲料中需含有至少 20% 蛋白质和 30% 脂肪。
原料 A 每千克成本为 3 元，含有 30% 蛋白质和 40% 脂肪；原料 B 每千克成本为 2 元，含有 10% 蛋白质和 20% 脂肪。
问：如何配比可以使每千克饲料的成本最低？

要求：

建立线性规划模型；

求出最优配比及最小成本。

In [15]:
import cvxpy as cp
import numpy as np

a=np.array([3,2])
b=np.array([[0.3,0.1],[0.4,0.2]])
c=np.array([0.2,0.3])
x=cp.Variable(2,pos=True)
obj=cp.Minimize(a@x)
cons=[b@x>=c,x>=0,cp.sum(x)==1]
prob=cp.Problem(obj,cons)
prob.solve()
print(x.value)
print(prob.value)

[0.5 0.5]
2.5000000012701697


In [ ]:
题目3：资源分配问题
某企业计划在三个项目中投资，总投资额为不超过 10 万元。
三个项目的单位投资回报率分别为 10%、12% 和 15%，
但项目 1 至多投资 4 万元，项目 2 至少投资 2 万元，项目 3 的投资不超过项目 1 的 1.5 倍。
问：应如何分配投资才能使回报最大？

In [21]:
import cvxpy as cp
import numpy as np

a=np.array([0.1,0.12,0.15])
x=cp.Variable(3,integer=True)
obj=cp.Maximize(a@x)
cons=[cp.sum(x)<=10,x>=0,x[0]<=4,x[1]>=2,x[2]<=1.5*x[0]]
prob=cp.Problem(obj,cons)
prob.solve()
print(x.value)
prob.value

[3. 3. 4.]


1.26

In [ ]:
题目4：运输问题
某公司有两个仓库（W1、W2），分别有 60 和 40 单位货物，
要送到三个客户（C1、C2、C3），需求分别为 30、50 和 20 单位。
单位运输成本如下：

    C1	C2	C3
W1	4	6	8
W2	5	4	3

问：应如何安排运输方案才能使总运输成本最小？

In [27]:
a=np.array([[4,6,8],[5,4,3]])
x=cp.Variable((2,3),integer=True)
obj=cp.Minimize(cp.sum(cp.multiply(a,x)))
cons=[x>=0,cp.sum(x[:,0])==30,cp.sum(x[:,1])==50,cp.sum(x[:,2])==20,cp.sum(x[0,:])==60,
      cp.sum(x[1,:])==40]
prob=cp.Problem(obj,cons)
prob.solve()
print(x.value)
prob.value

[[30. 30.  0.]
 [-0. 20. 20.]]


440.0

In [ ]:
题目5：混合问题（饮料调配）
某厂要调配一种新饮料，该饮料应含 500 毫升，总糖分含量不超过 50 克。厂里有三种原液：

A：含糖 10%，成本 1 元/100ml

B：含糖 5%，成本 0.8 元/100ml

C：含糖 0%，成本 0.5 元/100ml

要求最终饮料中 A 不超过 200ml，问应如何调配三种原液使成本最小？



In [28]:
x=cp.Variable(3,pos=True)
a=np.array([1,0.8,0.5])
b=np.array([0.1,0.05,0])
obj=cp.Minimize(a@x)
cons=[b@x<=50,x[0]<=200,x>=0,cp.sum(x)==500]
prob=cp.Problem(obj,cons)
prob.solve()
print(x.value)
prob.value


[2.89062183e-08 4.72462326e-07 4.99999999e+02]


250.00000015619185

In [ ]:
投资组合优化（最大最小型）
某投资者有 100 万资金，可投向 4 个项目，年回报率分别为 8%、10%、12%、15%。
每个项目的投资上限如下：

项目	最大投资（万元）
A	40
B	30
C	50
D	60

为了风险平衡，要求：

投入最多的项目与最少的项目之间的差距不超过 20 万；

项目 C 和 D 至少选择一个，且至少投 30 万；

目标：使总回报最大。

In [44]:
a=np.array([0.08,0.1,0.12,0.15])
b=np.array([40,30,50,60])
x=cp.Variable(4,integer=True)
y=cp.Variable(4,integer=True)
obj=cp.Maximize(a@x)
cons=[x>=0,cp.max(x)-cp.min(x)<=20,cp.sum(y[-2:])>=1,cp.sum(x[-2:])>=30,cp.sum(x)==100]
cons+=[x[i]<=b[i] for i in range(4)]
prob=cp.Problem(obj,cons)
prob.solve()
print(x.value)
prob.value


[15. 15. 35. 35.]


12.15

In [ ]:
题目 2：最小绝对误差拟合（L1范数）
有 5 个数据点 
1	2.1
2	3.9
3	6.1
4	8.2
5	9.7

你希望用线性模型 y=ax+b 拟合它们。

目标：使得所有点的绝对误差之和最小

要求建立线性规划模型，并给出最优a与b


In [48]:
a=np.array([1,2,3,4,5])
b=np.array([2.1,3.9,6.1,8.2,9.7])
x=cp.Variable(2)
y_pre=a*x[0]+x[1]
obj=cp.Minimize(cp.sum(cp.abs(y_pre-b)))
prob=cp.Problem(obj)
prob.solve()
print(x.value)
prob.value

[1.94905605 0.15094395]


0.7000000002370874

In [ ]:
题目 3：生产+运输联合优化（两阶段 LP）
某公司有两个工厂生产商品 A，每天产能上限分别为 100 和 120。生产成本分别为 2 和 3 元/单位。

商品要运往三个市场，需求分别为 80、90、50。运输成本如下（元/单位）：

市场1	市场2	市场3
工厂1	4	3	5
工厂2	6	2	4

要求：

满足所有市场需求

每个工厂最多生产其产能

工厂先生产，才能运输

目标：最小化总成本（生产 + 运输）

In [62]:
a=np.array([[4,3,5],[6,2,4]])
b=np.array([2,3])
x=cp.Variable((2,3),integer=True)
obj=cp.Minimize(cp.sum(cp.multiply(a,x))+cp.sum(2*x[0,:]+3*x[1,:]))
cons=[cp.sum(x,axis=1)<=np.array([100,120]),x>=0,cp.sum(x,axis=0)==np.array([80,90,50])]
prob=cp.Problem(obj,cons)
prob.solve()
print(x.value)
prob.value

[[80. 20.  0.]
 [ 0. 70. 50.]]


1280.0

In [ ]:
题目 4：最大化最小保障水平（公平分配问题）
公司分配资源（如奖金或预算）给 4 个部门，总量 100 单位。各部门期望分配分别为：30、40、50、60。
要求：
所有部门实际分配不超过期望；
尽量保证最不满意的部门尽可能满意（即最大化最小分配/期望的比例）
目标：
maxmin(𝑥𝑖/期望𝑖)
将该问题转化为线性规划模型。

In [54]:
a=np.array([30,40,50,60])
x=cp.Variable(4,pos=True)
obj=cp.Maximize(cp.min(x/a))
cons=[cp.sum(x)==100]
prob=cp.Problem(obj,cons)
prob.solve()
print(x.value)
prob.value

[16.66666662 22.2222224  27.77777785 33.33333312]


0.5555555520709244

In [ ]:
题目 5：0-1 整数线性规划（选址问题）
公司计划在 5 个城市中选址设立分公司，每个城市选址成本如下：

城市	成本（万元）
A	30
B	20
C	40
D	25
E	35

要求：

最多选 3 个城市；

至少选一个成本 ≤ 25 的城市；

选 A 必须选 B；

不允许同时选 C 和 D；

总成本不超过 80 万

目标：使服务人口最大（设有一个人口向量）

假设每个城市服务人口如下（单位：万人）：

城市	服务人口
A	50
B	40
C	70
D	60
E	65

In [61]:
a=np.array([30,20,40,25,35])
b=np.array([50,40,70,60,65])
x=cp.Variable(5,integer=True)
obj=cp.Maximize(cp.sum(x@b))
cons=[x>=0,x<=1,cp.sum(x)<=3,x[1]+x[3]>=1,cp.sum(a@x)<=80,
     x[0]<=x[1],x[2]+x[3]<=1]
prob=cp.Problem(obj,cons)
prob.solve()
print(x.value)
prob.value

[-0.  1. -0.  1.  1.]


165.0

# 课后练习题

In [2]:
#1

import cvxpy as cp
import numpy as np

a=np.array([0.3,0.18])
x=cp.Variable(2,pos=True)
obj=cp.Minimize(a@x)
cons=[x[1]<=6000/500/7,cp.sum(x)==1,x[0]>=0.2]
prob=cp.Problem(obj,cons)
prob.solve()
prob.value,x.value


(0.20400000007226474, array([0.2, 0.8]))

In [14]:
#2
a=np.array([[28,28,28,28],[45,45,45,10000],[60,60,10000,10000],[73,10000,10000,10000]])
x=cp.Variable((4,4),integer=True)
obj=cp.Minimize(cp.sum(cp.multiply(a,x)))
cons=[cp.sum(x[0,:])>=1500,
      cp.sum(x[0,1:])+cp.sum(x[1,:])>=1000,
      cp.sum(x[0,2:])+cp.sum(x[1,1:])+cp.sum(x[2,:])>=2000,
      cp.sum(x[0,3:])+cp.sum(x[1,2:])+cp.sum(x[2,1:])+cp.sum(x[3,:])>=1200,
      x>=0]
prob=cp.Problem(obj,cons)
prob.solve()
x.value,prob.value

(array([[  -0.,   -0.,  800., 1200.],
        [  -0.,   -0.,   -0.,   -0.],
        [  -0.,   -0.,   -0.,   -0.],
        [  -0.,   -0.,   -0.,   -0.]]),
 56000.0)

In [19]:
#3
x=cp.Variable(6,integer=True)
a=np.array([60,70,60,50,20,30])
obj=cp.Minimize(cp.sum(x))
cons=[x>=0,x[0]>=60]
for i in range(1,6):
    cons+=[x[i]+x[i-1]>=a[i]]
# cons=[x[0]>=60,x[1]+x[0]>=70,
#      x[1]+x[2]>=60,x[2]+x[3]>=50,
#      x[3]+x[4]>=20,x[4]+x[5]>=30,
#      x>=0]
s=cp.Problem(obj,cons)
s.solve()
x.value,s.value

(array([60., 10., 50., -0., 30., -0.]), 150.0)

In [1]:
#4

import numpy as np
import cvxpy as cp

a=np.array([[34,63,-10000,76,-10000,-10000,-10000],
[-10000,29,85,71,50,-10000,-10000],
[-10000,-10000,42,63,-10000,-10000,-10000],
[-10000,-10000,-10000,21,77,39,92],
[-10000,-10000,-10000,-10000,56,74,92],
[-10000,-10000,-10000,-10000,-10000,18,89],
[-10000,-10000,-10000,-10000,-10000,-10000,71]])
x=cp.Variable((7,7),integer=True)
obj=cp.Maximize(cp.sum(cp.multiply(a,x)))
cons=[cp.sum(x)==2,x>=0,x<=1,cp.sum(x,axis=0)<=1]
s=cp.Problem(obj,cons)
s.solve()
x.value,s.value

(array([[-0., -0., -0., -0., -0., -0., -0.],
        [-0., -0.,  1., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0.,  1.],
        [-0., -0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0., -0.]]),
 177.0)

## 模型如下
$fun=\sum_{i=1}^{4}(n_{i}*(r_{i}*x_{i}-(1-m_{i})*p_{i}*u_{i}-m_{i}*p_{i}*x_{i}))-max(\sum_{i=1}^{4}x_{i}*q_{i})$

s.t.
$sum(x_{i}+(1-m_{i})*p_{i}*u_{i}+m_{i}*p_{i}*x_{i})==10000$

$x_{i}>=0$

$n>=m$

$n>=0,n<=1,m>=0,m<=1$

In [127]:
#6
import cvxpy as cp
import numpy as np

# 决策变量
n = cp.Variable(4, integer=True)  # 是否投资 (0或1)
m = cp.Variable(4, integer=True)  # 是否超过阈值 (0或1)
x = cp.Variable(4, pos=True)   # 投资金额

# 参数
r = np.array([0.28, 0.21, 0.23, 0.25])  # 收益率
q = np.array([0.025, 0.015, 0.055, 0.026])  # 折扣因子
p = np.array([0.01, 0.02, 0.045, 0.065])  # 成本因子
u = np.array([103, 198, 52, 40])  # 阈值
M = 1e5  # 大M常数
eps = 1e-5  # 极小常数

# 辅助变量（用于线性化）
y = cp.Variable(4)  # y_i = n_i * x_i
w = cp.Variable(4)  # w_i = m_i * x_i

# 目标函数（线性化后）
revenue = cp.sum(cp.multiply(r, y))  # r_i * y_i = r_i * (n_i * x_i)
cost1 = cp.sum(cp.multiply(p*u,1-m))# x_i * (1 - m_i) * p_i * u_i
cost2 = cp.sum(cp.multiply(w, p))  # m_i * p_i * x_i
cost3 = cp.sum(cp.multiply(q, x))  # q_i * x_i

obj = cp.Maximize(revenue - cost1 - cost2 - cost3)

# 约束条件
cons = [
    # 总投资约束
    cp.sum(x)+cost1+cost2 == 10000,
    # 线性化约束：
    # 1. y_i = n_i * x_i （使用大M法）
    y <= M * n,
    y <= x,
    y >= x - M * (1 - n),
    y >= 0,
    # 2. w_i = m_i * x_i
    w <= M * m,
    w <= x,
    w >= x - M * (1 - m),
    w >= 0,
    # 3. m_i = 1 ⇔ x_i > u_i
    x <= u + M * m,
    x >= u * m + eps * (1 - m),
    # 4. n_i = 1 ⇔ x_i > 0
    x <= M * n,
    x >= eps * n,
    # 变量范围
    x >= 0,
    n >= 0, n <= 1,
    m >= 0, m <= 1,
    n >= m
]

# 求解
prob = cp.Problem(obj, cons)
prob.solve()

x.value,n.value,m.value,prob.value

C:\Users\zyh13\AppData\Roaming\Python\Python311\site-packages\cvxpy\expressions\expression.py:674: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 106 times so far.

  warnings.warn(msg, UserWarning)


(array([9296.62375248,  195.00001   ,  195.        ,  195.        ]),
 array([1., 1., 1., 1.]),
 array([ 1., -0.,  1.,  1.]),
 2368.0928213064344)